In [2]:
import numpy as np

To search array use where method

In [3]:
arr = np.array([1,2,3,4,5,4,4,4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6, 7], dtype=int64),)


In [5]:
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 0)
y = np.where(arr%2 == 1)
print(x)
print(y)

(array([1, 3, 5, 7], dtype=int64),)
(array([0, 2, 4, 6], dtype=int64),)


SEARCH SORTED USING searchsorted() method

In [7]:
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7)#returns index where 7 should be inserted
print(x)

2


SEARCHING FOR MULTIPLE VALUES

In [8]:
arr = np.array([1,3,5,7])
x = np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]
