using sort() we can sort the arrays in numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [3]:
arr = np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [4]:
arr = np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


SORTING 2-D ARRAYS

In [5]:
arr = np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
