Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless it is related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

In [1]:
from numpy import random

In [4]:
x = random.randint(100)
print(x)

32


In [11]:
x= random.rand()
print(x)

0.5383136070327633


Generate random array

In [12]:
x = random.randint(100,size=(5))
print(x)

[43 44 15 22 42]


Generate 2-D array

In [13]:
x = random.randint(100,size=(3,5))
print(x)

[[11 47 69 57  3]
 [27 29 37 68 35]
 [79 34 26 58 43]]


Floats

In [14]:
x=random.rand(5)
print(x)

[0.89563642 0.09401503 0.44922836 0.44716269 0.83119574]


In [15]:
x = random.rand(3,5)
print(x)

[[0.36639784 0.16198374 0.08055455 0.53604544 0.65784017]
 [0.58538782 0.72326163 0.47695021 0.42588512 0.26490211]
 [0.29430212 0.49660244 0.95696168 0.61451694 0.15177368]]


Generate random number from array

choice()

In [16]:
x = random.choice([3,5,7,9])
print(x)

7


In [17]:
x = random.choice([3,5,7,9],size=(3,5))
print(x)

[[3 3 5 7 3]
 [5 5 3 3 9]
 [3 9 7 7 5]]
