The random module offer methods that returns randomly generated data distributions.

--Random Distribution--
A random distribution is a set of random numbers that follow a certain probability density function.

using choice() method of random module

In [ ]:
from numpy import random

In [ ]:
x = random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))
print(x)

The sum of all probabilities should be 1

In [6]:
x = random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(3,5))
print(x)

[[7 7 7 5 5]
 [5 3 7 7 7]
 [5 7 7 3 5]]
