In [1]:
import numpy as np


In [5]:
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])

newarr = np.add(arr1,arr2)
print(newarr)

newar = np.subtract(arr1,arr2)
print(newar)

newarm = np.multiply(arr1,arr2)
print(newarm)

neward = np.divide(arr1,arr2)
print(neward)

newarp = np.power(arr1,arr2)
print(newarp)

newmod = np.mod(arr1,arr2)
print(newmod)

newarrr = np.remainder(arr1,arr2)
print(newarrr)

# quotient and mod
newarqm = np.divmod(arr1,arr2)
print(newarqm)

[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]
[200 231 264 299 336 375]
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
[ 1661992960   602408795           0  1487897765  1090519040 -1144744561]
[10 11 12 13 14 15]
[10 11 12 13 14 15]
(array([0, 0, 0, 0, 0, 0]), array([10, 11, 12, 13, 14, 15]))


In [6]:
# absolute values
arr = np.array([-1,-5,-8,-3,-7,4,5])
newarr = np.absolute(arr)
print(newarr)

[1 5 8 3 7 4 5]
